
CUDA_VISIBLE_DEVICES=0 python correctness_gen.py --model_name_or_path Salesforce/codegen-2B-multi --batch_size 25
CUDA_VISIBLE_DEVICES=0 python correctness_gen.py --model_name_or_path Salesforce/codegen-2B-nl --batch_size 25
CUDA_VISIBLE_DEVICES=0 python correctness_gen.py --model_name_or_path Salesforce/codegen-2B-mono --batch_size 25
CUDA_VISIBLE_DEVICES=0 python correctness_gen.py --model_name_or_path Salesforce/codegen-6B-multi --batch_size 10
CUDA_VISIBLE_DEVICES=0 python correctness_gen.py --model_name_or_path Salesforce/codegen-6B-nl --batch_size 10
CUDA_VISIBLE_DEVICES=0 python correctness_gen.py --model_name_or_path Salesforce/codegen-6B-mono --batch_size 10
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codet5p-220m-py --batch_size 50
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codet5p-220m --batch_size 50
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codet5p-770m-py --batch_size 25 
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codet5p-770m --batch_size 25 
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codet5p-2b --batch_size 20
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codegen-350M-mono --batch_size 50 
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codegen-350M-multi --batch_size 50 
CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codegen-350M-nl --batch_size 50 
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codet5p-6b
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codegen2-1B
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codegen2-3_7B
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path Salesforce/codegen2-7B
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path codellama/CodeLlama-7b-hf
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path codellama/CodeLlama-7b-Instruct-hf
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path codellama/CodeLlama-7b-Python-hf
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path codellama/CodeLlama-13b-Python-hf
# CUDA_VISIBLE_DEVICES=0  python correctness_gen.py --model_name_or_path codellama/CodeLlama-13b-Python-hf